# Generated by Django 4.1 on 2022-10-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rut',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
