# Generated by Django 4.1 on 2022-10-27 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DeviceModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.devicemodel'),
        ),
        migrations.DeleteModel(
            name='DevicePatient',
        ),
    ]
