# Generated by Django 4.1 on 2022-10-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_devicemodel_delete_devicepatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='DeviceModel',
            new_name='device',
        ),
    ]
